package com.poc.shoppingcart.enums;

/**
 * @author Sayanta.Ganguly
 *
 */
public enum OrderStates {
	/*
	 * FULFILLED, CHOICE_REGISTRATION, REGISTERED, UNREGISTERED, CART_SAVED_IN_TEMP,
	 * FORK_REGISTRATION, JOIN_REGISTRATION, CHECK_REGISTRATION, TASK,
	 */
	
	
	
	
	
	SUBMITTED,
	CART_SAVED,
	CART_RETRIEVED,
	CART_UPDATED,
	PAID,
	CANCELLED
}
